alias gst='git status'
alias ggpush='git push origin "$(git-branch-current 2> /dev/null)"'
alias ggpull='git pull origin "$(git-branch-current 2> /dev/null)"'
alias gd='git diff'
alias z='fasd_cd -d'
