alias gst='git status'
alias ggpush='git push origin "$(git_branch_current 2> /dev/null)"'
alias ggpull='git pull origin "$(git_branch_current 2> /dev/null)"'
alias gd='git diff'
alias z='fasd_cd -d'
